chore: date and timestamp func added
porterin/reason-utils pull request #106
Opened 2021-09-23 12:21 UTC by porter473

2021-09-23 12:21 UTC, porter473 commented on src/entities/date/Date.re
> +let toString = (~format: string, ~date: t) =>
Indenation Change

2021-09-23 12:22 UTC, porter473 commented on src/entities/date/Date.re
> +let getDateTimeAfterElapsedTime =
Indentation Change

2021-09-24 05:30 UTC, kd4001 requested changes

2021-09-24 05:30 UTC, kd4001 commented on src/entities/date/Date.re
> +let toString = (~format: string, ~date: t) =>
Should not be there. Please ping the vscode settings. 
Make sure this setting is active.
"reason_language_server.format_width": 100,

2021-09-24 05:30 UTC, kd4001 commented on src/entities/date/Date.re
> +  (Js.Date.now() -. day->float_of_int *. 24.0 *. 60.0 *. 60.0 *. 1000.0)
Try using Moment.subtract. You might have to work around duration.

2021-09-24 07:17 UTC, kd4001 approved these changes

2021-09-24 07:28 UTC, merged