Pending tag 2.5.3 changes for Select
porterin/reason-utils pull request #115
Opened 2021-12-06 07:13 UTC by ashutheone

2021-12-13 21:44 UTC, kd4001 requested changes

2021-12-13 21:44 UTC, kd4001 commented on src/components/generic/form/form-input/FormInputProps.re
> +  onOpen: unit => unit,
Does it work for date and time?
Also it doesn't work for radio button and check box. So it's not common input props. So I recommend to move to select props.

2021-12-13 21:44 UTC, kd4001 commented on src/components/generic/Adornment.re
> +];
Can we abstract out these types and have our own types ?

2021-12-17 10:49 UTC, porter473 commented on src/components/generic/form/form-input/FormInputProps.re
> +  onOpen: unit => unit,
We are keeping this for now in the `inputProps` as we can have a use case where these callbacks are being used in Date/Time picker.

2021-12-17 10:49 UTC, merged