Added make_props in AccordionTypes and onOpen prop
porterin/reason-utils pull request #140
Opened 2022-03-01 11:19 UTC by bhavyamm01

2022-03-01 11:23 UTC, porter473 commented on src/components/generic/accordion/AccordionTypes.re
> +      ~footer: React.element,
use `React.null` for footer

2022-03-14 11:50 UTC, porter473 commented on examples/ExampleTable.re
> +      onOpen: _ => Js.log("Accordion working 2")
use `make_props`

2022-03-14 11:53 UTC, Prateek13727 commented on src/components/generic/accordion/Accordion.re
> +module AccordionModule = {
rename to `AccordionWrapper`. The suffix Module is not adding any value to the name

2022-03-14 11:59 UTC, porter473 requested changes

2022-03-14 11:59 UTC, porter473 commented on examples/ExampleTable.re
> +    }
use `make_props`

2022-03-14 11:59 UTC, porter473 commented on src/components/generic/accordion/AccordionTypes.re
> +      ~header,
Mention the `header` type. Lets make it a practice to define the function's parameter types

2022-03-14 11:59 UTC, porter473 commented on examples/ExampleTable.re
> +    }
If the added code is part of testing, then we can remove it.

2022-03-14 13:45 UTC, merged