Base version - CRM migrations-1.0.0
porterin/reason-utils pull request #3
Opened 2020-12-04 13:26 UTC by Prateek13727

2020-12-17 07:32 UTC, ashutheone requested changes

2020-12-17 07:32 UTC, ashutheone commented on src/components/styles/abstract/_colorPalette.scss
> +
Top section of color palette is not generic. It is specific to a use-case.
Either these should be renamed or moved to repo where they are used.

'status colors' section has names which are suitable for a top level palette.

2020-12-17 07:32 UTC, ashutheone commented on src/components/styles/abstract/_mixins.scss
> +}
These don't belong here.

2020-12-17 07:32 UTC, ashutheone commented on src/components/styles/abstract/_mixins.scss
> +}
Or should be renamed

2020-12-17 07:32 UTC, ashutheone commented on src/components/styles/base/_base.scss
> +
Not necessarily

2020-12-17 07:32 UTC, ashutheone commented on src/components/styles/base/_utilities.scss
> +
Use case specific

2020-12-17 07:32 UTC, ashutheone commented on src/components/styles/components/_header.scss
> +}
Isn't this for workspace?

2020-12-17 07:32 UTC, ashutheone commented on src/components/styles/main.scss
> +@import "abstract/variables";
Where is main.scss used?

2020-12-17 07:32 UTC, ashutheone commented on src/components/styles/main.scss
> +@import "abstract/variables";
This way it will be a bulky import always. We need to split it up.

2020-12-17 07:32 UTC, ashutheone commented on src/entities/OptionList.re
> +module type SelectListConfig = {type uniqueIdType;};
What is this for? This is probably not similar to other entities.

2020-12-17 07:32 UTC, ashutheone commented on src/helper-modules/csv-parser/CsvRow.re
> +type t = ReMapUtils.StringMap.t(string);
Can we make a types folder for this and others below?

2020-12-17 07:32 UTC, ashutheone commented on src/helper-modules/reasonML/FlatResult.re
> +let let_ = Belt.Result.flatMap;
Remove duplicate

2020-12-17 07:32 UTC, ashutheone commented on src/helper-modules/sentry/Sentry.js
> +  /Cannot read property \'\d+\' of null/i
Remove these

2020-12-17 07:32 UTC, ashutheone commented on src/utils/ArrayUtils.re
> +let firstN = (range: int, inputArray: array('a)): array('a) =>
is this needed?

2020-12-17 07:32 UTC, ashutheone commented on src/utils/FormValidationUtils.re
> +let validateCallerNumber = (caller_number: string): Belt.Result.t(string, string) => {
rename to validateMobileNUmber

2020-12-17 07:32 UTC, ashutheone commented on src/utils/ValidationHelper.re
> +module MobileNumber = {
This is a repeat

2020-12-17 07:56 UTC, kd4001 commented on src/components/custom/cards/card_deprecated/CardComponentV2.re
> +  </div>;
Yes

2020-12-17 08:29 UTC, kd4001 commented on src/components/custom/event-tracker/publisher/EventTracker.re
> +let getGaEventPayload =
If the changes are to me made in future he can make in this repo only and test it in spotcrm with version bump.

2020-12-17 08:35 UTC, kd4001 commented on src/components/generic/accordion/CrmAccordianStatusLabel.re
> +let getStatusClassName = (status: CrmAccordionStatus.t): string => {
This need to be refactored. This is CRM specific code but it is has been put as Accordion component part. 
Weird !!!!!
Will refactor this.

2020-12-17 08:37 UTC, kd4001 commented on src/components/generic/form/LabelV4.re
> +[@react.component]
Not required in spotCRM. Please verify that it's not used in fronted-website or virality or any other

2020-12-17 08:38 UTC, kd4001 commented on src/components/styles/abstract/_colorPalette.scss
> +
I think these are porter theme based which Rajiv uses. Any suggestions for changes?

2020-12-17 08:40 UTC, kd4001 commented on src/components/styles/base/_base.scss
> +
Breaking changes. Any suggestions how to remove this ?

2020-12-17 08:44 UTC, kd4001 commented on src/components/styles/components/_header.scss
> +}
This is for having common porter banner.

2020-12-17 08:48 UTC, kd4001 commented on src/components/styles/main.scss
> +@import "abstract/variables";
All the scss in imported to single main.scss and who ever wants to use any mixin or any property will import it..
Kind of blunder.
Will be moving component specific css to component folder and will be imported there.
_colorPallete, mixins, variable, utilities will still be imported to a single scss file and then to use any of the these you need to have single import.

2020-12-17 08:50 UTC, kd4001 commented on src/entities/OptionList.re
> +module type SelectListConfig = {type uniqueIdType;};
Used for termination and suspension reasons json decoder types. Legacy code.

2020-12-17 09:01 UTC, kd4001 commented on src/utils/ArrayUtils.re
> +let firstN = (range: int, inputArray: array('a)): array('a) =>
Yes

2020-12-17 10:36 UTC, Prateek13727 commented on src/components/styles/base/_utilities.scss
> +
we can address this once we refactor css.

2020-12-17 10:38 UTC, Prateek13727 commented on src/components/styles/abstract/_colorPalette.scss
> +
These are generic color themes Ashutosh. going forward we will use/add the colors to this palette only for consistency

2020-12-17 10:39 UTC, Prateek13727 commented on src/components/styles/abstract/_mixins.scss
> +}
any suggestions for the names ?

2020-12-17 10:46 UTC, Prateek13727 commented on src/utils/FormValidationUtils.re
> +let validateCallerNumber = (caller_number: string): Belt.Result.t(string, string) => {
@kd4001 ek baar check kar le if we can use a single logic for mobile number validation

2020-12-17 10:49 UTC, Prateek13727 commented on src/helper-modules/sentry/Sentry.js
> +  /Cannot read property \'\d+\' of null/i
@kd4001 take the update from master for this file. udhar updated hay

2020-12-17 11:19 UTC, kd4001 commented on src/helper-modules/sentry/Sentry.js
> +  /Cannot read property \'\d+\' of null/i
okay

2020-12-18 06:46 UTC, Prateek13727 commented on src/components/custom/error/ErrorDisplayComponentV2.re
> +[@react.component]
Let's remove ErrorComponent altogether. @ashutheone we may need to test 2 RnR pages

2020-12-18 06:47 UTC, Prateek13727 commented on src/components/custom/event-tracker/publisher/EventTracker.re
> +let getGaEventPayload =
We can make new changes on top of it

2020-12-29 10:35 UTC, merged