Date picker: value type Js.date.t -> option(Js.date.t)
porterin/reason-utils pull request #52
Opened 2021-03-05 08:26 UTC by dwarika-porter

2021-03-05 11:50 UTC, ashutheone requested changes

2021-03-05 11:50 UTC, ashutheone commented on src/components/generic/form/form-input/FormDateInput.re
> +  value: option(Js.Date.t),
Lets make a v2 component with a deadline for 15th April to replace v1 or to be reverted.

2021-03-05 11:50 UTC, ashutheone commented on src/components/generic/date-time-picker/DatePicker.re
> +
Dont place this module here..
Maybe move this to DateTime utils or Option utils or something related.

2021-03-05 12:32 UTC, ashutheone requested changes

2021-03-05 12:32 UTC, ashutheone commented on src/components/generic/form/form-input/FormDateInputV2.re
> +let make = (~input_props: FormInputProps.t('b, 'c), ~date_props: t) => {
Use make_props like [here](https://github.com/porterin/reason-utils/blob/master/src/components/generic/form/form-input/FormSelectInput.re)

2021-03-05 12:32 UTC, ashutheone commented on src/components/generic/date-time-picker/DatePickerV2.re
> +      variant="inline"
pass this as prop and make it's default value inline in make_props

2021-03-05 12:32 UTC, ashutheone commented on src/components/generic/date-time-picker/DatePickerV2.re
> +      inputVariant="outlined"
For each value being set here.. make them default through make_props

2021-03-08 11:38 UTC, dwarika-porter commented on src/components/generic/form/form-input/FormDateInput.re
> +  value: option(Js.Date.t),
Comment added

2021-03-12 11:38 UTC, kd4001 approved these changes

2021-03-15 11:36 UTC, Prateek13727 commented on src/components/generic/date-time-picker/DatePickerV2.re
> +        Js.Null.fromOption(value)
value -> Js.Null.fromOption -> OptionTypeUtils.OptionMomentToMomentMap.optionMomentToMoment

2021-03-15 11:36 UTC, Prateek13727 commented on src/components/generic/date-time-picker/DatePickerV2.re
> +        Js.Null.fromOption(value)
more comprehensible

2021-03-16 07:19 UTC, merged