adding date interface
porterin/reason-utils pull request #61
Opened 2021-04-07 08:39 UTC by Prateek13727

2021-04-07 16:53 UTC, shubhamgupta731 requested changes

2021-04-07 16:53 UTC, shubhamgupta731 commented on src/entities/date/MomentUtils.rei
> +type t
Since its a `DateUtils` the type `t` over here should be the same as `Date.t`

2021-04-07 16:53 UTC, shubhamgupta731 commented on src/entities/date/MomentUtils.rei
> +type t
Also `MomentUtils` is not exposing adding any extra functionality that is already provided by `Moment`. `toDate` and `Date.make` are doing the same thing.

2021-04-08 06:09 UTC, Prateek13727 commented on src/entities/date/MomentUtils.re
> +open MomentRe;
the idea is that tomorrow if we use dateFns library, we create a dateFnsUtils.  Two advantages ->
-> This will give the Date module, the flexibility to use multiple Date libraries
-> when we change the library the only place that needs to change is Date module function

2021-04-13 12:01 UTC, ashutheone requested changes

2021-04-13 12:01 UTC, ashutheone commented on src/entities/date/MomentUtils.re
> +open MomentRe;
Better to retain this and let it be returned by a functor in Date.re
This will ensure our vision of supporting alternate date libs

2021-04-13 12:13 UTC, Prateek13727 commented on src/entities/date/MomentUtils.re
> +open MomentRe;
yup, we are retaining this. already discussed with Shubham

2021-04-13 12:17 UTC, Prateek13727 commented on src/entities/date/Date.re
> +let make = (~value: string, ~format: string) => {
I get it, something on the lines of dependency injection. This use case is still developing. we can also have a scenario where we might use the mix of both the libraries. let's address this as we add more methods and address more use-cases

2021-04-15 11:33 UTC, kd4001 commented on src/entities/date/MomentUtils.re
> +let momentWithFormat = (date: string, format: string) => {
Since Moment.t in neither an input  or output in this file than what's the use-case of this file.

2021-04-23 09:17 UTC, Prateek13727 commented on src/entities/date/MomentUtils.re
> +let momentWithFormat = (date: string, format: string) => {
removed Js.Date.t from MomentUtils.t and moved to Date.t

2021-06-18 07:59 UTC, closed without merging